#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>

const char *palavras_mais_usadas[] = {
    "DA", "nossa", "vida,", "em", "meio", "da", "jornada,", "[1]",
    "Achei-me", "numa", "selva", "tenebrosa,", "[2]",
    "Tendo", "perdido", "a", "verdadeira", "estrada.",
    "Dizer", "qual", "era", "é", "cousa", "tão", "penosa,",
    "Desta", "brava", "espessura", "a", "asperidade,",
    "Que", "a", "memória", "a", "relembra", "inda", "cuidosa.",
    "Na", "morte", "há", "pouco", "mais", "de", "acerbidade;",
    "Mas", "para", "o", "bem", "narrar", "lá", "deparado",
    "De", "outras", "cousas", "que", "vi,", "direi", "verdade.",
    "Contar", "não", "posso", "como", "tinha", "entrado;",
    "Tanto", "o", "sono", "os", "sentidos", "me", "tomara,",
    "Quando", "hei", "o", "bom", "caminho", "abandonado.",
    "Depois", "que", "a", "uma", "colina", "me", "cercara,",
    "Onde", "ia", "o", "vale", "escuro", "terminando,",
    "Que", "pavor", "tão", "profundo", "me", "causara.",
    "Ao", "alto", "olhei,", "e", "já,", "de", "luz", "banhando,",
    "Vi-lhe", "estar", "às", "espaldas", "o", "planeta,",
    "Que,", "certo,", "em", "toda", "parte", "vai", "guiando.",
    "Então", "o", "assombro", "um", "tanto", "se", "aquieta,",
    "Que", "do", "peito", "no", "lago", "perdurava,",
    "Naquela", "noite", "atribulada,", "inquieta.",
    "E", "como", "quem", "o", "anélito", "esgotava",
    "Sobre", "as", "ondas,", "já", "salvo,", "inda", "medroso",
    "Olha", "o", "mar", "perigoso", "em", "que", "lutava,",
    "O", "meu", "ânimo", "assim,", "que", "treme", "ansioso,",
    "Volveu-se", "a", "remirar", "vencido", "o", "espaço",
    "Que", "homem", "vivo", "jamais", "passou", "ditoso.",
    "Tendo", "já", "repousado", "o", "corpo", "lasso,",
    "Segui", "pela", "deserta", "falda", "avante;",
    "Mais", "baixo", "sendo", "o", "pé", "firme", "no", "passo.",
    "Eis", "da", "subida", "quase", "ao", "mesmo", "instante",
    "Assoma", "ágil", "e", "rápida", "pantera", "[3]",
    "Tendo", "a", "pele", "por", "malhas", "cambiante.",
    "Não", "se", "afastava", "de", "ante", "mim", "a", "fera;",
    "E", "em", "modo", "tal", "meu", "caminhar", "tolhia,",
    "Que", "atrás", "por", "vezes", "eu", "tornar", "quisera.",
    "No", "céu", "a", "aurora", "já", "resplandecia,",
    "Subia", "o", "sol,", "dos", "astros", "rodeado,",
    "Seus", "sócios,", "quando", "o", "Amor", "divino", "um", "dia",
    "A", "tais", "primores", "movimento", "há", "dado.",
    "Me", "infundiam", "desta", "arte", "alma", "esperança",
    "Da", "fera", "o", "dorso", "alegre", "e", "mosqueado,",
    "A", "hora", "amena", "e", "a", "quadra", "doce", "e", "mansa.",
    "De", "um", "leão", "de", "repente", "surge", "o", "aspecto,", "[4]",
    "Que", "ao", "meu", "peito", "o", "pavor", "de", "novo", "lança.",
    "Que", "me", "investisse", "então", "cuido", "inquieto;",
    "Com", "fome", "e", "raiva", "atroz", "fronte", "levanta;",
    "Tremer", "parece", "o", "ar", "ao", "seu", "conspeto.",
    "Eis", "surge", "loba,", "que", "de", "magra", "espanta;", "[5]",
    "De", "ambições", "todas", "parecia", "cheia;",
    "Foi", "causa", "a", "muitos", "de", "miséria", "tanta!",
    "Com", "tanta", "intensa", "torvação", "me", "enleia",
    "Pelo", "terror,", "que", "o", "cenho", "seu", "movia,",
    "Que", "a", "mente", "à", "altura", "não", "subir", "receia.",
    "Como", "quem", "lucro", "anela", "noite", "e", "dia,",
    "Se", "acaso", "o", "tempo", "de", "perder", "lhe", "chega,",
    "Rebenta", "em", "pranto", "e", "triste", "se", "excrucia,",
    "A", "fera", "assim", "me", "fez,", "que", "não", "sossega;",
    "Pouco", "a", "pouco", "me", "investe", "até", "lançar-me",
    "Lá", "onde", "o", "sol", "se", "cala", "e", "a", "luz", "me", "nega.",
    "Quando", "ao", "vale", "eu", "já", "ia", "baquear-me",
    "Alguém", "fraco", "de", "voz", "diviso", "perto,", "[6]",
    "Que", "após", "largo", "silêncio", "quer", "falar-me.",
    "Tanto", "que", "o", "vejo", "nesse", "grão", "deserto,",
    "—", "Tem", "compaixão", "de", "mim\"", "—", "bradei", "transido", "—",
    "\"Quem", "quer", "que", "sejas,", "sombra", "ou", "homem", "certo!\"",
    "\"Homem", "não", "sou\"", "tornou-me", "—", "\"mas", "hei", "sido,",
    "Pais", "lombardos", "eu", "tive;", "sempre", "amada",
    "Mântua", "lhes", "foi;", "haviam", "lá", "nascido.",
    "\"Nasci", "de", "Júlio", "em", "era", "retardada,",
    "Vivi", "em", "Roma", "sob", "o", "bom", "Augusto,",
    "Quando", "em", "deuses", "havia", "a", "crença", "errada.",
    "\"Poeta,", "decantei", "feitos", "do", "justo",
    "Filho", "de", "Anquíses,", "que", "de", "Tróia", "veio,",
    "Depois", "que", "Ílion", "soberbo", "foi", "combusto.",
    "\"Mas", "por", "que", "tornas", "da", "tristeza", "ao", "meio?",
    "Por", "que", "não", "vais", "ao", "deleitoso", "monte,",
    "Que", "o", "prazer", "todo", "encerra", "no", "seu", "seio?\"",
    "\"—", "Oh!", "Virgílio,", "tu", "és", "aquela", "fonte",
    "Donde", "em", "rio", "caudal", "brota", "a", "eloqüência?\"",
    "Falei,", "curvando", "vergonhoso", "a", "fronte.", "—",
    "\"Ó", "dos", "poetas", "lustre,", "honra,", "eminência!",
    "Valham-me", "o", "longo", "estudo,", "o", "amor", "profundo",
    "Com", "que", "em", "teu", "livro", "procurei", "ciência!",
    "\"És", "meu", "mestre,", "o", "modelo", "sem", "segundo;",
    "Unicamente", "és", "tu", "que", "hás-me", "ensinado;",
    "O", "belo", "estilo", "que", "honra-me", "no", "mundo.",
    "\"A", "fera", "vês", "que", "o", "passo", "me", "há", "vedado;",
    "Sábio", "famoso,", "acude", "ao", "perseguido!",
    "Tremo", "no", "pulso", "e", "veias,", "transtornado!\"",
    "Respondeu,", "do", "meu", "pranto", "condoído;",
    "\"Te", "convém", "outra", "rota", "de", "ora", "avante",
    "Para", "o", "lugar", "selvagem", "ser", "vencido.",
    "\"A", "fera,", "que", "te", "faz", "bradar", "tremante,",
    "Aqui", "passar", "não", "deixa", "impunemente;",
    "Tanto", "se", "opõe,", "que", "mata", "o", "caminhante.",
    "\"Tem", "tão", "má", "natureza,", "é", "tão", "furente,",
    "Que", "os", "apetites", "seus", "jamais", "sacia,",
    "E", "fome,", "impando,", "mais", "que", "de", "antes", "sente.",
    "\"Com", "muitos", "animais", "se", "consorcia,",
    "Há-de", "a", "outros", "se", "unir", "té", "ser", "chegado",
    "Lebréu,", "que", "a", "leve", "à", "hórrida", "agonia.",
    "\"Por", "ouro", "ou", "por", "poder", "nunca", "tentado",
    "Saber,", "virtude,", "amor", "terá", "por", "norte,",
    "Sendo", "entre", "Feltro", "e", "Feltro", "potentado.", "[7]",
    "\"Será", "da", "humilde", "Itália", "amparo", "forte,",
    "Por", "quem", "Camila", "a", "virgem", "dera", "a", "vida,",
    "Turno", "Eurialo,", "Niso", "acharam", "morte.",
    "\"Por", "ele,", "em", "toda", "parte,", "repelida",
    "Irá", "lançar-se", "no", "infernal", "assento,",
    "Donde", "foi", "pela", "Inveja", "conduzida.",
    "\"Agora,", "por", "teu", "prol,", "eu", "tenho", "o", "intento",
    "De", "levar-te", "comigo;", "ir-te-ei", "guiando",
    "Pela", "estância", "do", "eterno", "sofrimento,",
    "\"Onde,", "estridentes", "gritos", "escutando,",
    "Verás", "almas", "antigas", "em", "tortura",
    "Segunda", "morte", "a", "brados", "suplicando.",
    "\"Outros", "ledos", "verás,", "que,", "em", "prova", "dura",
    "Das", "chamas,", "inda", "esperam", "ter", "o", "gozo",
    "De", "Deus", "no", "prêmio", "da", "imortal", "ventura.",
    "\"Se", "lá", "subir", "quiseres,", "um", "ditoso",
    "Espírito,", "melhor", "te", "será", "guia,", "[8]",
    "Quando", "eu", "deixar-te,", "ao", "reino", "glorioso.",
    "\"Do", "céu", "o", "Imperador,", "a", "rebeldia",
    "Minha", "à", "lei", "castigando,", "não", "consente",
    "Que", "eu", "da", "cidade", "sua", "haja", "a", "alegria.",
    "\"Em", "toda", "parte", "impera", "onipotente,",
    "Mas", "tem", "no", "Empíreo", "sua", "augusta", "sede:",
    "Feliz,", "por", "ele,", "o", "eleito", "à", "glória", "ingente!\"",
    "—", "\"Vate,", "rogo-te\"", "—", "eu", "disse", "—", "\"me", "concede,",
    "Por", "esse", "Deus,", "que", "nunca", "hás", "conhecido,",
    "Porque", "este", "e", "maior", "mal", "de", "mim", "se", "arrede.",
    "\"Que,", "até", "onde", "disseste", "conduzido,",
    "À", "porta", "de", "São", "Pedro", "eu", "vá", "contigo",
    "E", "veja", "os", "maus", "que", "houveste", "referido\".",
    "Move-se", "o", "Vate", "então,", "após", "o", "sigo.",
    "FORA-se", "o", "dia;", "e", "o", "ar,", "se", "enevoando,",
    "Aos", "animais,", "que", "vivem", "sobre", "a", "terra,",
    "As", "fadigas", "tolhia;", "eu", "só,", "velando,",
    "Me", "aparelhava", "a", "sustentar", "a", "guerra",
    "Da", "jornada,", "assim", "como", "da", "piedade,",
    "Que", "vai", "pintar", "memória,", "que", "não", "erra.",
    "Ó", "Musas!", "Ó", "do", "gênio", "potestade!",
    "Valei-me!", "Aqui,", "ó", "mente,", "que", "guardaste",
    "Quanto", "vi,", "mostra", "a", "egrégia", "qualidade.",
    "\"Poeta\",", "—", "assim", "falei,", "—", "\"que", "começaste",
    "A", "guiar-me,", "vê", "bem", "se", "em", "mim", "persiste",
    "Calor", "que,", "à", "empresa", "que", "me", "fias,", "baste.",
    "\"Que", "o", "pai", "do", "Sílvio", "fora,", "referiste,", "[9]",
    "Corrutível", "ainda,", "até", "o", "inferno",
    "Sem", "perder", "o", "que", "em", "corpo", "humano", "existe.",
    "\"Se", "do", "mal", "assim", "quis", "o", "imigo", "eterno,",
    "Origem", "vendo", "nele", "do", "alto", "efeito,",
    "O", "que", "e", "o", "qual,", "segundo", "o", "que", "discerno,",
    "\"Pela", "razão", "bem", "pode", "ser", "aceito;",
    "Que", "para", "Roma", "e", "o", "império", "se", "fundarem",
    "Fora", "no", "céu", "por", "genitor", "eleito;",
    "\"À", "qual", "e", "ao", "qual", "cabia", "aparelharem,",
    "Dizendo-se", "a", "verdade,", "o", "lugar", "santo",
    "Aos", "que", "do", "maior", "Pedro", "o", "sólio", "herdaram.",
    "\"Nessa", "empresa,", "em", "que", "o", "hás", "louvado", "tanto,",
    "Cousas", "ouviu,", "de", "que", "surgiu", "motivo",
    "Ao", "seu", "triunfo", "e", "ao", "pontifício", "manto.",
    "\"Lá", "foi", "o", "Vaso", "Eleito", "ainda", "vivo:", "[10]",
    "Conforto", "ia", "buscar,", "à", "fé,", "que", "à", "estrada",
    "Da", "salvação", "princípio", "é", "decisivo.",
    "\"Por", "que", "irei?", "Quem", "permite", "esta", "jornada?",
    "Enéias,", "Paulo", "sou?", "Essa", "ventura",
    "Nem", "eu,", "nem", "outrem", "crê", "ser-me", "adatada.",
    "\"Receio,", "pois", "seja", "ato", "de", "loucura,",
    "Se", "eu", "me", "resigno", "a", "cometer", "a", "empresa.",
    "Supre,", "és", "sábio,", "o", "que", "digo", "em", "frase", "escura\".",
    "Como", "quem", "ora", "quer,", "ora", "despreza,",
    "Sua", "alma", "a", "idéias", "novas", "tem", "disposta,",
    "Mostrando", "aos", "seus", "desígnios", "estranheza,",
    "Assim", "fiz", "eu", "na", "tenebrosa", "encosta,",
    "Porque,", "pensando,", "abandonava", "o", "intento,",
    "Formado", "à", "pressa,", "que", "ora", "me", "desgosta.",
    "\"Do", "teu", "dizer", "se", "atinjo", "o", "entendimento\"",
    "—", "Do", "magnânimo", "a", "sombra", "me", "tornava,", "—",
    "\"Eivado", "estás", "de", "ignóbil", "sentimento,",
    "\"Que", "do", "homem", "muita", "vez", "faz", "alma", "ignava,",
    "Das", "honrosas", "ações", "o", "desviando,",
    "Qual", "sombra,", "que", "o", "corcel", "ao", "medo", "trava.",
    "\"Desse", "temor", "livrar-te", "desejando,",
    "Por", "que", "vim", "te", "direi", "e", "quanto", "ouvido",
    "Hei", "logo", "ao", "ver-te", "mísero", "lutando.",
    "\"No", "Limbo", "era", "suspenso:", "eis", "requerido",
    "Por", "Dama", "fui", "tão", "bela,", "tão", "donosa,",
    "Que", "as", "ordens", "suas", "presto", "lhe", "hei", "pedido.",
    "\"Brilhavam", "mais", "que", "a", "estrela", "radiosa",
    "Os", "seus", "olhos;", "suave", "assim", "dizia",
    "De", "anjo", "com", "voz,", "falando-me", "piedosa:",
    "—", "\"De", "Mântua", "alma", "cortês,", "que", "inda", "hoje", "em", "dia",
    "No", "mundo", "gozas", "fama", "tão", "sonora,",
    "Que,", "enquanto", "existir", "mundo,", "mais", "se", "amplia,",
    "\"Amigo", "meu,", "que", "a", "sorte", "desadora,",
    "Pela", "deserta", "falda", "indo,", "impedido",
    "De", "medo,", "atrás", "os", "passos", "volta", "agora.",
    "\"Temo", "que", "esteja", "tanto", "já", "perdido,",
    "Que", "tarde", "eu", "tenha", "vindo", "a", "socorrê-lo,",
    "Pelo", "que", "lá", "no", "céu", "dele", "hei", "sabido.",
    "\"Parte,", "pois,", "e", "com", "teu", "discurso", "belo",
    "E", "quanto", "o", "salvar", "possa", "do", "perigo",
    "Lhe", "acode;", "e", "me", "console", "o", "teu", "desvelo.",
    "\"Sou", "Beatriz,", "que", "envia-te", "ao", "que", "digo,",
    "De", "lugar", "venho", "a", "que", "voltar", "desejo:",
    "Amor", "conduz-me", "e", "faz-me", "instar", "contigo.",
    "\"Voltando", "ao", "meu", "Senhor,", "em", "todo", "o", "ensejo",
    "Repetirei", "louvor,", "que", "hás", "merecido\".", "—",
    "\"Tornei-lhe,", "quando", "já", "calar-se", "a", "vejo:",
    "—", "\"Senhora", "da", "virtude,", "a", "quem", "tem", "sido", "[11]",
    "Dado", "só", "que", "proceda", "a", "espécie", "humana",
    "Quanto", "é", "no", "mundo", "sublunar", "contido,",
    "\"Tanto", "praz-me", "a", "ordem", "que", "de", "ti", "dimana,",
    "Que,", "já", "cumprida,", "houvera", "inda", "demora:",
    "Em", "me", "abrir", "teu", "querer", "não", "mais", "te", "afana.",
    "\"Diz-me,", "porém,", "por", "que", "razão,", "Senhora,",
    "Baixar", "a", "este", "centro", "hás", "resolvido",
    "Do", "céu,", "a", "que", "ardes", "por", "voltar", "agora\".",
    "—", "\"Se", "queres", "tanto", "ser", "esclarecido",
    "Eu", "te", "direi\"", "—", "tornou-me", "—", "\"frase", "breve",
    "Por", "que", "sem", "medo", "às", "trevas", "hei", "descido.",
    "\"Somente", "as", "cousas", "recear", "se", "deve",
    "Que", "a", "outrem", "podem", "ser", "causa", "de", "dano",
    "Não", "das", "mais:", "a", "temor", "a", "causa", "é", "leve.",
    "\"De", "Deus", "favor", "criou-me", "soberano",
    "Tal,", "que", "a", "vossa", "miséria", "não", "me", "empece",
    "Nem", "deste", "incêndio", "assalta", "o", "fogo", "insano.",
    "\"Nobre", "Dama", "há", "no", "céu,", "que", "compadece", "[12]",
    "O", "mal,", "a", "que", "te", "envio;", "e", "tanto", "implora,",
    "Que", "lá", "decreto", "austero", "se", "enternece.",
    "—", "\"Volvendo-se", "a", "Luzia,", "assim", "a", "exora:", "[13]",
    "\"O", "teu", "servo", "fiel", "tanto", "periga,",
    "Que", "ao", "teu", "amparo", "o", "recomendo", "agora\".", "—",
    "\"Luzia,", "sempre", "do", "que", "é", "mau", "imiga",
    "Ergue-se", "e", "ao", "lugar", "foi,", "em", "que", "eu", "sentada",
    "Ao", "lado", "estava", "de", "Raquel", "antiga.",
    "\"De", "Deus", "vero", "louvor!\"", "—", "diz-me", "apressada", "—",
    "\"Por", "que", "não", "socorrer", "quem", "te", "amou", "tanto,",
    "Que", "só", "por", "ti", "deixou", "do", "vulgo", "a", "estrada?",
    "\"Não", "lhe", "ouves,", "Beatriz,", "o", "amargo", "pranto?",
    "Não", "vês", "que", "junto", "ao", "rio", "é", "combatido,",
    "Que", "ao", "mar", "não", "corre,", "por", "mortal", "espanto?\"", "—",
    "\"Os", "danos,", "tão", "veloz,", "não", "tem", "fugido",
    "Ninguém,", "nem", "procurado", "o", "que", "deseja,",
    "Como", "eu,", "em", "tendo", "vozes", "tais", "ouvido;",
    "\"O", "trono", "meu", "deixei,", "por", "que", "te", "veja,",
    "Fiada", "em", "teus", "discursos", "eloqüentes,",
    "Honra", "tua", "e", "de", "quem", "te", "ouvindo", "esteja\".", "—",
    "\"Assim", "falava", "e", "os", "olhos", "fulgentes",
    "Com", "lágrimas", "a", "mim", "ela", "volvia,",
    "Para", "apressar-me", "a", "vir", "assaz", "potentes.",
    "\"A", "ti", "vim,", "pois,", "como", "ela", "requeria;",
    "Da", "fera", "te", "livrei,", "que", "da", "colina",
    "Tão", "perto", "já,", "teus", "passos", "impedia.",
    "\"Que", "fazes,", "pois?", "Por", "que,", "por", "que", "domina",
    "Tanta", "fraqueza", "o", "peito", "espavorido?",
    "Por", "que", "ao", "valor", "tua", "alma", "não", "se", "inclina,",
    "\"Quando", "és", "pelas", "três", "santas", "protegido,",
    "Que", "na", "corte", "do", "céu", "por", "ti", "se", "esmeram,",
    "E", "gozar", "tanto", "bem", "lhe", "é", "prometido?\"", "—",
    "Quais", "flores,", "que,", "fechadas,", "se", "abateram",
    "Da", "noite", "ao", "frio,", "e,", "quando", "o", "sol", "aquece,",
    "Erguem-se", "abertas", "na", "hástea,", "tais", "como", "eram,",
    "Tal", "meu", "valor", "renova", "e", "fortalece.",
    "Tanto", "ardimento", "o", "coração", "me", "aviva,",
    "Que", "exclamei,", "como", "quem", "jamais", "temesse:",
    "\"Ó", "Dama", "em", "socorrer-me", "compassiva!",
    "E", "tu,", "que", "a", "voz", "lhe", "ouvindo,", "obedeceste,",
    "Cortês", "ao", "rogo", "e", "com", "vontade", "ativa,",
    "\"Por", "teu", "dizer", "no", "peito", "me", "acendeste",
    "Desejo", "tal", "de", "vir,", "que", "sou", "tornado",
    "Ao", "propósito,", "a", "que", "antes", "me", "trouxeste.",
    "\"Vai,", "pois", "nosso", "querer", "’stá", "combinado.",
    "Serás", "meu", "guia,", "meu", "senhor,", "meu", "mestre!\"",
    "Disse-lhe", "assim.", "Moveu-se", "ele;", "ao", "seu", "lado",
    "Pelo", "caminho", "entrei", "alto", "e", "silvestre.",
    "\"POR", "mim", "se", "vai", "das", "dores", "à", "morada,",
    "Por", "mim", "se", "vai", "ao", "padecer", "eterno,",
    "Por", "mim", "se", "vai", "à", "gente", "condenada.",
    "\"Moveu", "Justiça", "o", "Autor", "meu", "sempiterno,",
    "Formado", "fui", "por", "divinal", "possança,",
    "Sabedoria", "suma", "e", "amor", "supremo.",
    "No", "existir,", "ser", "nenhum", "a", "mim", "se", "avança,",
    "Não", "sendo", "eterno,", "e", "eu", "eternal", "perduro:",
    "Deixai,", "ó", "vós", "que", "entrais,", "toda", "a", "esperança!\"",
    "Estas", "palavras,", "em", "letreiro", "escuro,",
    "Eu", "vi,", "por", "cima", "de", "uma", "porta", "escrito.",
    "\"Seu", "sentido\"", "—", "disse", "eu", "—", "\"Mestre", "me", "é", "duro\"",
    "Tornou", "Virgílio,", "no", "lugar", "perito:",
    "—", "\"Aqui", "deixar", "convém", "toda", "suspeita;",
    "Todo", "ignóbil", "sentir", "seja", "proscrito.",
    "\"Eis", "a", "estância,", "que", "eu", "disse,", "às", "dores", "feita,",
    "Onde", "hás", "de", "ver", "atormentada", "gente,",
    "Que", "da", "razão", "à", "perda", "está", "sujeita\".",
    "Pela", "mão", "me", "travando", "diligente,",
    "Com", "ledo", "gesto", "e", "coração", "me", "erguia,",
    "E", "aos", "mistérios", "guiou-me", "incontinênti.",
    "Por", "esse", "ar", "sem", "estrelas", "irrompia",
    "Soar", "de", "pranto,", "de", "ais,", "de", "altos", "gemidos:",
    "Também", "meu", "pranto,", "de", "os", "ouvir,", "corria.",
    "Línguas", "várias,", "discursos", "insofridos,",
    "Lamentos,", "vozes", "roucas,", "de", "ira", "os", "brados,",
    "Rumor", "de", "mãos,", "de", "punhos", "estorcidos,",
    "Nesses", "ares,", "pra", "sempre", "enevoados,",
    "Retumbavam", "girando", "e", "semilhando",
    "Areais", "por", "tufão", "atormentados.",
    "A", "mente", "aquele", "horror", "me", "perturbando,",
    "Disse", "a", "Virgílio:", "—", "\"Ó", "Mestre,", "que", "ouço", "agora?",
    "\"Quem", "são", "esses,", "que", "a", "dor", "está", "prostrando?\"", "—",
    "\"Deste", "mísero", "modo\"", "—", "tornou", "—", "\"chora",
    "Quem", "viveu", "sem", "jamais", "ter", "merecido",
    "Nem", "louvor,", "nem", "censura", "infamadora.",
    "\"De", "anjos", "mesquinhos", "coro", "é-lhes", "unido,", "[14]",
    "Que", "rebeldes", "a", "Deus", "não", "se", "mostraram,",
    "Nem", "fiéis,", "por", "si", "sós", "havendo", "sido\".",
    "\"Desdouro", "aos", "céus,", "os", "céus", "os", "desterraram;",
    "Nem", "o", "profundo", "inferno", "os", "recebera,",
    "De", "os", "ter", "consigo", "os", "maus", "se", "gloriaram\".",
    "—", "\"Que", "dor", "tão", "viva", "deles", "se", "apodera,",
    "Que", "aos", "carpidos", "motivo", "dá", "tão", "forte?\"", "—",
    "\"Serei", "breve", "em", "dizer-to\"", "—", "me", "assevera.", "—",
    "\"Não", "lhes", "é", "dado", "nunca", "esperar", "morte;",
    "É", "tão", "vil", "seu", "viver", "nessa", "desgraça,",
    "Que", "invejam", "de", "outros", "toda", "e", "qualquer", "sorte.",
    "\"No", "mundo", "o", "nome", "seu", "não", "deixou", "traça;",
    "A", "Clemência,", "a", "Justiça", "os", "desdenharam.",
    "Mais", "deles", "não", "falemos:", "olha", "e", "passa\".",
    "Bandeira", "então", "meus", "olhos", "divisaram,",
    "Que,", "a", "tremular,", "tão", "rápida", "corria,",
    "Que", "avessa", "a", "toda", "pausa", "a", "imaginaram.",
    "E", "após,", "tão", "basta", "multidão", "seguia,",
    "Que,", "destruído", "houvesse", "tanta", "gente",
    "A", "morte,", "acreditado", "eu", "não", "teria.",
    "Alguns", "já", "distinguira:", "eis,", "de", "repente,",
    "Olhando,", "a", "sombra", "conheci", "daquele",
    "Que", "a", "grã", "renúncia", "fez", "ignobilmente.", "[15]",
    "Soube", "logo,", "o", "que", "ao", "certo", "me", "revele,",
    "Que", "era", "a", "seita", "das", "almas", "aviltadas,",
    "Que", "os", "maus", "odeiam", "e", "que", "Deus", "repele.",
    "Nunca", "tiveram", "vida", "as", "desgraçadas;",
    "Sempre,", "nuas", "estando,", "as", "torturavam",
    "De", "vespas", "e", "tavões", "as", "ferroadas.",
    "Os", "rostos", "seus", "as", "lágrimas", "regavam,",
    "Misturadas", "de", "sangue:", "aos", "pés", "caindo,",
    "A", "imundos", "vermes", "o", "repasto", "davam.",
    "De", "um", "largo", "rio", "à", "margem", "dirigindo",
    "A", "vista,", "de", "almas", "divisei", "cardume.",
    "—", "\"Mestre,", "declara,", "aos", "rogos", "me", "anuindo,",
    "\"Que", "turba", "é", "essa\"", "—", "eu", "disse", "—", "\"e", "qual", "costume",
    "Tanto", "a", "passar", "a", "torna", "pressurosa,",
    "Se", "bem", "discirno", "ao", "duvidoso", "lume?\"", "—",
    "Tornou-me:", "—", "\"Explicação", "minuciosa",
    "Darei,", "quando", "tivermos", "atingido",
    "Do", "Aqueronte", "a", "ribeira", "temerosa\".",
    "Então,", "baixos", "os", "olhos", "e", "corrido",
    "Fui,", "de", "importuno", "a", "culpa", "receando,",
    "Té", "o", "rio,", "em", "silêncio", "recolhido.",
    "Eis", "vejo", "a", "nós", "em", "barca", "se", "acercando,",
    "De", "cãs", "coberto", "um", "velho", "—", "\"Ó", "condenados,",
    "Ai", "de", "vós!", "—", "alta", "grita", "levantando.",
    "\"O", "céu", "nunca", "vereis,", "desesperados:",
    "Por", "mim", "à", "treva", "eterna,", "na", "outra", "riva,",
    "Sereis", "ao", "fogo,", "ao", "gelo", "transportados.",
    "\"E", "tu", "que", "estás", "aqui,", "ó", "alma", "viva,",
    "De", "entre", "estes", "que", "são", "mortos,", "já", "te", "ausenta!\"",
    "Como", "não", "lhe", "obedeço", "à", "voz", "esquiva,",
    "\"Por", "outra", "via", "irás\"", "—", "ele", "acrescenta", "—",
    "\"Ao", "porto,", "onde", "acharás", "fácil", "transporte;",
    "Lá", "pássaras", "sem", "barca", "menos", "lenta\".", "—",
    "\"Não", "te", "agastes,", "Caronte!", "Desta", "sorte",
    "Se", "quer", "lá", "onde\"", "—", "disse-lhe", "o", "meu", "Guia", "—",
    "\"Quem", "pode", "ordena.", "E", "nada", "mais", "te", "importe\".",
    "Sereno,", "ouvido,", "o", "gesto", "se", "fazia",
    "Da", "lívida", "lagoa", "ao", "nauta", "idoso,",
    "Quem", "em", "círculos", "de", "fogo", "olhos", "volvia.",
    "As", "desnudadas", "almas", "doloroso",
    "O", "gesto", "descorou;", "dentes", "rangeram",
    "Logo", "em", "lhe", "ouvindo", "o", "vozear", "raivoso.",
    "Blasfemaram", "de", "Deus", "e", "maldisseram",
    "A", "espécie", "humana,", "a", "pátria,", "o", "tempo,", "a", "origem",
    "Da", "origem", "sua,", "os", "pais", "de", "quem", "nasceram.",
    "Todas", "no", "pranto", "acerbo,", "em", "que", "se", "afligem,",
    "Se", "acolhem", "juntas", "ao", "lugar", "tremendo,",
    "Dos", "maus", "destinos,", "que", "se", "não", "corrigem.",
    "Caronte,", "os", "ígneos", "olhos", "revolvendo,",
    "Lhes", "acenava", "e", "a", "todos", "recebia:",
    "Remo", "em", "punho,", "as", "tardias", "vai", "batendo.",
    "Como", "no", "outono", "a", "rama", "principia",
    "As", "flores", "a", "perder", "té", "ser", "despida,",
    "Dando", "à", "terra", "o", "que", "à", "terra", "pertencia,",
    "Assim", "de", "Adam", "a", "prole", "pervertida,",
    "Da", "praia", "um", "após", "outro", "se", "enviavam,",
    "Qual", "ave", "dos", "reclamos", "atraída.",
    "Sobre", "as", "túrbidas", "águas", "navegavam;",
    "E", "pojado", "não", "tinham", "no", "outro", "lado,",
    "Mais", "turbas", "já", "no", "oposto", "se", "apinhavam.",
    "\"Aqui", "meu", "filho\"", "—", "disse", "o", "Mestre", "amado", "—",
    "\"concorrem", "quantos", "há", "colhido", "a", "morte,",
    "De", "toda", "a", "terra,", "tendo", "a", "Deus", "irado.",
    "\"O", "rio", "prontos", "buscam", "desta", "sorte,",
    "De", "Deus", "tanto", "a", "justiça", "os", "punge", "e", "excita,",
    "Tornando-se", "o", "temor", "anelo", "forte!",
    "\"Alma", "inocente", "aqui", "jamais", "transita,",
    "E,", "se", "Caronte", "contra", "ti", "se", "assanha,",
    "Patente", "a", "causa", "está,", "que", "tanto", "o", "irrita\".",
    "Assim", "falava;", "a", "lúrida", "campanha",
    "Tremeu", "e", "foi", "tão", "forte", "o", "movimento,",
    "Que", "do", "medo", "o", "suor", "ainda", "me", "banha.",
    "Da", "terra", "lacrimosa", "rompeu", "vento,",
    "Que", "um", "clarão", "respirou", "avermelhado;",
    "Tolhido", "então", "de", "todo", "o", "sentimento,",
    "Caí,", "qual", "homem", "que", "é", "do", "sono", "entrado.",
    "DESSE", "profundo", "sono", "fui", "tirado",
    "Por", "hórrido", "estampido,", "estremecendo",
    "Como", "quem", "é", "por", "força", "despertado.",
    "Ergui-me,", "e,", "os", "olhos", "quietos", "já", "volvendo,",
    "Perscruto", "por", "saber", "onde", "me", "achava,",
    "E", "a", "tudo", "no", "lugar", "sinistro", "atendo.",
    "A", "verdade", "é", "que", "então", "na", "borda", "estava",
    "Do", "vale", "desse", "abismo", "doloroso,",
    "Donde", "brado", "de", "infindos", "ais", "troava.",
    "Tão", "escuro,", "profundo", "e", "nebuloso",
    "Era,", "que", "a", "vista", "lhe", "inquirindo", "o", "fundo,",
    "Não", "distinguia", "no", "antro", "temeroso.",
    "\"Eia!", "Baixemos,", "pois,", "da", "treva", "ao", "mundo!\"", "—",
    "O", "Poeta", "então", "disse-me", "enfiando", "—",
    "\"Eu", "descerei", "primeiro,", "tu", "segundo\".", "—",
    "Tornei-lhe,", "a", "palidez", "sua", "notando:",
    "\"Como", "hei-de", "ir,", "se", "és", "de", "espanto", "dominado,",
    "Quando", "conforto", "estou", "de", "ti", "sperando?\"", "—",
    "\"Dos", "que", "lá", "são", "o", "angustioso", "estado",
    "Causa", "a", "que", "vês", "no", "rosto", "meu", "impressa,",
    "Piedade,", "medo", "não,", "como", "hás", "cuidado.",
    "\"Vamos:", "longa", "a", "jornada", "exige", "pressa\".",
    "Entrou,", "e", "eu", "logo,", "o", "círculo", "primeiro",
    "Em", "que", "o", "abismo", "a", "estreitar-se", "já", "começa,",
    "Escutei:", "não", "mais", "pranto", "lastimeiro",
    "Ouvi;", "suspiros", "só,", "que", "murmuravam,",
    "Vibrando", "do", "ar", "eterno", "o", "espaço", "inteiro.",
    "Pesares", "sem", "martírio", "os", "motivavam",
    "De", "varões", "e", "de", "infantes,", "de", "mulheres",
    "Nas", "multidões,", "que", "ali", "se", "apinhoavam.",
    "\"Conhecer\"", "—", "meu", "bom", "Mestre", "diz", "—", "\"não", "queres",
    "Quais", "são", "os", "que", "assim", "vês", "ora", "sofrendo?",
    "Antes", "de", "avante", "andar", "convém", "saberes",
    "\"Que", "não", "pecaram:", "boas", "obras", "tendo",
    "Acham-se", "aqui;", "faltou-lhes", "o", "batismo,",
    "Portal", "da", "fé,", "em", "que", "és", "ditoso", "crendo.",
    "\"Na", "vida", "antecedendo", "o", "Cristianismo,",
    "Devido", "culto", "a", "Deus", "nunca", "prestaram:",
    "Também", "sou", "dos", "que", "penam", "neste", "abismo.",
    "\"Por", "tal", "defeito", "—", "os", "mais", "nos", "não", "mancharam", "—",
    "Perdemo-nos:", "a", "pena", "é", "desesp’rança,",
    "Desejos,", "que", "para", "sempre", "se", "frustaram\".",
    "Ouvi-lo,", "em", "dor", "o", "coração", "me", "lança,",
    "Pois", "muitos", "conheci", "de", "alta", "valia,",
    "A", "quem", "do", "Limbo", "a", "suspenção", "alcança.",
    "\"Ó", "Mestre!", "Ó", "meu", "Senhor!", "diz-me", "—", "inquiria,",
    "Para", "ter", "da", "certeza", "o", "firme", "esteio",
    "À", "fé,", "que", "os", "erros", "todos", "desafia,",
    "\"Por", "seu", "merecimento", "ou", "pelo", "alheio",
    "Daqui", "alguém", "ao", "céu", "já", "tem", "subido?\"",
    "Da", "mente", "minha", "ao", "alvo", "o", "Mestre", "veio,",
    "E", "falou-me:", "\"Des’pouco", "aqui", "trazido,",
    "Descer", "súbito", "vi", "forte", "guerreiro;",
    "De", "triunfal", "coroa", "era", "cingido.",
    "\"Almas", "levou", "—", "do", "nosso", "pai", "primeiro,",
    "Abel,", "Noé,", "Moisés,", "que", "legislara,",
    "Abraam,", "na", "fé,", "na", "obediência", "inteiro,",
    "\"Davi,", "que", "sobre", "o", "povo", "hebreu", "reinara,",
    "Israel", "com", "seu", "pai", "e", "a", "prole", "basta,",
    "E", "Raquel,", "por", "quem", "tanto", "se", "afanara.",
    "\"Para", "a", "glória", "outros", "muitos", "mais", "afasta",
    "Do", "Limbo;", "e", "sabe", "tu", "que", "antes", "não", "fora",
    "Salvo", "quem", "pertencera", "à", "humana", "casta\".",
    "Andávamos,", "enquanto", "isto", "memora,",
    "Sem", "parar,", "pela", "selva", "penetrando,",
    "Selva", "de", "almas,", "que", "aumenta", "de", "hora", "em", "hora,",
    "E", "da", "entrada", "não", "longe", "ainda", "estando,",
    "Eis", "um", "clarão", "brilhante", "divisamos",
    "Das", "trevas", "o", "hemisfério", "alumiando.",
    "Dali", "distantes", "ainda", "nos", "achamos",
    "Não", "tanto,", "que", "eu", "não", "discernisse", "em", "parte",
    "Que", "à", "sede", "de", "almas", "nobres", "caminhamos.",
    "\"Ó", "tu,", "que", "és", "honra", "da", "ciência", "e", "da", "arte,",
    "Quem", "são\"", "—", "disse", "—", "\"os", "que,", "aos", "outros", "preferidos,",
    "Privilégio", "tamanho", "assim", "disparte?\"",
    "Falou", "Virgílio:", "\"—", "Assim", "são", "distinguidos",
    "Do", "céu,", "que", "atende", "à", "fama", "alta", "e", "preclara,",
    "Com", "que", "foram", "na", "terra", "engrandecidos\".",
    "Eis", "voz", "escuto", "sonorosa", "e", "clara:",
    "\"Honrai", "todos", "o", "altíssimo", "poeta!",
    "A", "sombra", "sua", "torna,", "que", "ausentara\".",
    "Quatro", "sombras", "notei,", "quando", "aquieta",
    "O", "rumor,", "que", "a", "nós", "vinham:", "nos", "semblantes",
    "Nem", "prazer,", "nem", "tristeza", "se", "interpreta.",
    "E", "disse", "o", "Mestre,", "após", "alguns", "instantes:",
    "\"Aquele", "vê,", "que,", "qual", "monarca", "ufano,",
    "Empunha", "espada", "e", "os", "três", "deixa", "distantes.",
    "É", "Homero,", "o", "poeta", "soberano;",
    "O", "satírico", "Horácio", "é", "o", "outro,", "e", "ao", "lado",
    "Ovídio,", "em", "lugar", "último", "Lucano.",
    "Como", "lhes", "cabe", "o", "nome", "assinalado",
    "Que", "soou", "nessa", "voz", "há", "pouco", "ouvida,",
    "Me", "honrando,", "honrosa", "ação", "têm", "praticado\".",
    "A", "bela", "escola", "assim", "vi", "reunida",
    "Do", "Mestre", "egrégio", "do", "sublime", "canto,", "[17]",
    "Águia", "em", "seu", "vôo", "além", "dos", "mais", "erguida.",
    "Discursado", "entre", "si", "tendo", "algum", "tanto,",
    "A", "mim", "volveram", "gracioso", "o", "gesto:",
    "Sorriu", "Virgílio,", "dessa", "mostra", "ao", "encanto.",
    "Mais", "foi-me", "alto", "conceito", "manifesto,",
    "Quando", "acolher-me", "ao", "grêmio", "seu", "quiseram,",
    "Entre", "eles", "me", "cabendo", "o", "lugar", "sexto.",
    "Té", "o", "clarão", "comigo", "se", "moveram,",
    "Prática", "havendo,", "que", "omitir", "é", "belo,",
    "Sublime", "no", "lugar,", "onde", "a", "teceram.",
    "Chegamos", "junto", "a", "um", "fúlgido", "castelo",
    "Sete", "vezes", "de", "muro", "alto", "cercado:",
    "Cinge-o", "ribeiro", "lindo,", "mas", "singelo.",
    "Passei-o", "a", "pé", "enxuto;", "acompanhado",
    "Entrei", "por", "sete", "portas,", "caminhando",
    "De", "fresca", "relva", "até", "ameno", "prado.",
    "Graves,", "pausados", "olhos", "meneando",
    "Stavam", "sombras", "de", "aspecto", "majestoso,",
    "Com", "voz", "suave", "rara", "vez", "falando.",
    "A", "um", "lado,", "sobre", "viso", "luminoso",
    "Subimo-nos:", "de", "lá", "se", "divisava",
    "Dessas", "almas", "o", "bando", "numeroso.",
    "No", "verde", "esmalte", "o", "Mestre", "me", "indicava",
    "Egrégias", "sombras:", "inda", "me", "extasia",
    "O", "prazer", "com", "que", "vê-los", "exultava.",
    "Eletra", "vi", "de", "heróis", "na", "companhia,", "[18]",
    "Enéias", "com", "Heitor", "e", "guarnecido", "[19]",
    "Grifanhos", "olhos", "César", "nos", "volvia.",
    "Pentesiléia", "vi", "e", "o", "rosto", "ardido", "[20]",
    "De", "Camila,", "e", "sentado", "o", "rei", "Latino", "[21]",
    "Junto", "a", "Lavinia", "estava", "enternecido.",
    "Notei", "Márcia,", "Lucrécia", "e", "o", "que", "Tarquino", "[22]",
    "Lançou,", "Cornélia", "e", "Júlia;", "retirado", "[23]",
    "De", "todos", "demorava", "Saladino.", "[24]",
    "Alçando", "os", "olhos,", "de", "respeito", "entrado,",
    "O", "Mestre", "vejo", "dos", "que", "mais", "se", "acimam", "[25]",
    "Em", "saber,", "de", "filósofos", "cercado.",
    "Todos", "com", "honra", "e", "acatamento", "o", "estimam.",
    "Aqui", "Platão", "e", "Sócrates", "estavam,",
    "Que", "na", "grandeza", "mais", "se", "lhe", "aproximam.",
    "Demócrito,", "o", "atomista,", "acompanhavam",
    "Tales,", "Zeno,", "Heráclito", "e", "Anaxagora.",
    "Empédocle", "e", "Diógenes", "falavam,",
    "Dióscoris,", "o", "que", "a", "natura", "outrora",
    "Sábio", "estudara,", "Orfeu,", "Túlio", "eloqüente,", "[26]",
    "Sêneca,", "o", "douto,", "que", "a", "moral", "explora,",
    "Lívio,", "Euclides,", "Hipócrates", "ingente,",
    "Ptolomeu,", "Galeno", "e", "o", "Avicena;", "[27]",
    "Averróis,", "nos", "comentos", "sapiente.",
    "Resenha", "não", "me", "é", "dado", "fazer", "plena",
    "De", "todos;", "longo", "o", "assunto", "está-me", "urgindo,",
    "E", "a", "ser", "omisso", "muita", "vez", "condena.",
    "A", "companhia", "então", "se", "dividindo,",
    "Comigo", "o", "Mestre", "outra", "vereda", "trilha,",
    "Do", "ar", "sereno", "ao", "ar,", "que", "treme,", "vindo:",
    "Chegados", "somos", "onde", "luz", "não", "brilha.",
    "DESCI", "desta", "arte", "ao", "círculo", "segundo,",
    "Que", "o", "espaço", "menos", "largo", "compreendia,",
    "Onde", "o", "pungir", "da", "dor", "é", "mais", "profundo.",
    "Lá", "stava", "Minos", "e", "feroz", "rangia:", "[28]",
    "Examinava", "as", "culpas", "desde", "a", "entrada,",
    "Dava", "a", "sentença", "como", "ilhais", "cingia.",
    "Ante", "ele", "quando", "uma", "alma", "desditada",
    "Vem,", "seus", "crimes", "confessa-lhe", "em", "chegando,",
    "Com", "perícia", "em", "pecados", "consumada.",
    "Lugar", "no", "inferno,", "Minos,", "lhe", "adaptando,",
    "Do", "abismo", "o", "círc’lo", "arbitra,", "a", "que", "pertença,",
    "Pelas", "voltas", "da", "cauda", "graduando.",
    "Sempre", "muitas", "se", "lhe", "acham", "na", "presença;",
    "Cada", "qual", "tem", "sua", "vez", "de", "ser", "julgada,",
    "Diz,", "ouve,", "cai,", "se", "some", "sem", "detença.",
    "Minos,", "logo", "me", "vendo,", "iroso", "brada,",
    "Do", "grave", "ofício", "no", "ato", "sobrestando:",
    "—", "\"Ó", "tu,", "que", "vens", "das", "dores", "à", "morada;",
    "\"Olha", "como", "entras", "e", "em", "quem", "stás", "fiando:",
    "Não", "te", "engane", "do", "entrar", "tanta", "largueza!\"",
    "—", "\"Por", "que", "falar\"", "—", "meu", "guia", "diz", "—", "\"gritando?\"",
    "\"Vedar", "não", "tentes", "a", "fatal", "empresa:",
    "Assim", "se", "quer", "lá", "onde", "o", "que", "se", "ordena",
    "Se", "cumpre.", "Assaz", "te", "seja", "esta", "certeza!\"",
    "Eis", "já", "começo", "da", "infernal", "geena",
    "A", "ouvir", "os", "lamentos:", "sou", "chegado",
    "Onde", "intenso", "carpir", "me", "aviva", "a", "pena.",
    "Em", "lugar", "de", "luz", "mudo", "tenho", "entrado:",
    "Rugia,", "como", "faz", "mar", "combatido",
    "Dos", "ventos,", "pelo", "ímpeto", "encontrado.",
    "Da", "tormenta", "o", "furor,", "nunca", "abatido,",
    "Perpetuamente", "as", "almas", "torce,", "agita,",
    "Molesta,", "em", "seus", "embates", "recrescido.",
    "Quando", "à", "borda", "do", "abismo", "as", "precipita,",
    "Ais,", "soluços,", "lamentos", "vão", "rompendo.",
    "Blasfema", "a", "Deus", "a", "multidão", "maldita.",
    "Ouvi", "que", "estão", "no", "padecer", "horrendo",
    "Os", "que", "aos", "vícios", "da", "carne", "se", "entregavam,",
    "Razão", "aos", "apetites", "submetendo.",
    "Quais", "estorninhos,", "que", "a", "voar", "se", "travam",
    "Em", "densos", "bandos", "na", "estação", "já", "fria,",
    "Em", "rodopio", "as", "almas", "volteavam,",
    "Ao", "capricho", "do", "vento,", "que", "as", "trazia.",
    "De", "pausa", "não,", "de", "menos", "dor", "a", "esp’rança",
    "Conforto", "lhes", "não", "dá", "nessa", "agonia.",
    "Como", "nos", "ares", "longa", "série", "avança",
    "De", "grous,", "que", "vão", "cantado", "o", "seu", "grasnido,",
    "Assim", "no", "gemer", "seu,", "que", "não", "descansa,",
    "Traz", "o", "tufão", "as", "sombras", "desabrido.",
    "—", "\"Mestre\"", "—", "disse", "eu", "—", "\"quais", "almas", "são", "aquelas",
    "Que", "o", "vendaval", "fustiga", "denegrido?\"",
    "—", "\"A", "primeira\"", "—", "tornou", "Virgílio", "—", "\"entre", "elas",
    "De", "quem", "notícias", "ter", "desejarias,",
    "Regeu", "nações,", "diversas", "nas", "loquelas.",
    "\"De", "luxúria", "fez", "tantas", "demasias",
    "Que", "em", "lei", "dispôs", "ser", "lícito", "e", "agradável",
    "Para", "desculpa", "às", "torpes", "fantasias.",
    "\"Semíramis", "chamou-se:", "o", "trono", "estável", "[29]",
    "Herdou", "de", "Nino", "e", "foi", "a", "sua", "esposa.",
    "Do", "Soldão", "teve", "a", "terra", "memorável.",
    "\"A", "morte", "deu-se", "a", "outra,", "de", "amorosa,", "[30]",
    "Às", "cinzas", "de", "Siqueu", "traidora", "e", "infida;",
    "Cleópatra", "após", "vem", "luxuriosa\".", "[31]",
    "Helena", "vi,", "a", "causa", "fementida", "[32]",
    "De", "tanto", "mal,", "e", "Aquiles", "celebrado",
    "Que", "teve", "por", "amor", "a", "extrema", "lida.",
    "Páris,", "Tristão", "e", "um", "bando", "assinalado", "[33]",
    "De", "sombras", "me", "indicou,", "nomes", "dizendo,",
    "Que", "à", "sepultura", "amor", "tinha", "arrojado.",
    "A", "compaixão", "me", "estava", "confrangendo,",
    "Dessas", "damas", "e", "antigos", "cavaleiros",
    "Nomes", "ouvindo", "e", "mágoas", "conhecendo.",
    "Então", "disse", "eu:", "—", "\"Poeta,", "aos", "companheiros",
    "Dois,", "que", "ali", "vêm,", "falar", "muito", "desejo:", "[34]",
    "Ao", "vento", "ser", "parecem", "tão", "ligeiros!\"",
    "\"Hás", "de", "ter\"", "—", "me", "tornou", "—", "\"asado", "ensejo,",
    "Quando", "forem", "mais", "perto;", "então", "lhes", "pede",
    "Pelo", "amor", "que", "os", "uniu:", "virão", "sem", "pejo\".", "—",
    "Quando", "acercar-se", "o", "vento", "lhes", "concede",
    "A", "voz", "alcei:", "—", "\"Ó!", "vinde,", "almas", "aflitas,",
    "Falar-nos,", "se", "alta", "lei", "não", "vo-lo", "impede\".", "—",
    "Quais", "pombas,", "que", "saudosas", "de", "asas", "fitas,",
    "Ao", "doce", "ninho,", "em", "vôo", "despedido,",
    "Vão", "pelo", "ar,", "aos", "desejos", "seus", "adstritas:",
    "Tais", "saíram", "da", "turba,", "em", "que", "era", "Dido,",
    "A", "nós", "as", "duas", "sombras", "se", "inclinando,",
    "Tanto", "as", "moveu", "da", "voz", "o", "tom", "sentido!",
    "—", "\"Entre", "beni’no,", "compassivo", "e", "brando,",
    "Que", "nos", "vem", "visitar", "por", "este", "ar", "perso,",
    "Tendo", "nós", "dado", "o", "sangue", "ao", "mundo", "infando,",
    "\"Se", "amigo", "o", "Senhor", "fosse", "do", "universo,",
    "Da", "paz", "aos", "rogos", "nossos,", "gozarias,",
    "Pois", "te", "enternece", "o", "nosso", "mal", "perverso.",
    "\"Enquanto", "o", "vento", "é", "quedo,", "o", "que", "dirias",
    "Havemos", "nós", "de", "ouvir", "atentamente;",
    "Diremos", "quanto", "ouvir", "desejarias.",
    "\"Onde,", "a", "paz", "desejando,", "o", "Pado", "ingente",
    "Com", "seus", "vassalos", "para", "o", "mar", "descende,",
    "A", "terra,", "em", "que", "hei", "nascido,", "está", "jacente.",
    "\"Amor,", "que", "os", "corações", "súbito", "prende,",
    "Este", "inflamou", "por", "minha", "formosura,",
    "Que", "roubaram-me:", "o", "modo", "inda", "me", "ofende.",
    "\"Amor,", "em", "paga", "exige", "igual", "ternura,",
    "Tomou", "por", "ele", "em", "tal", "prazer", "meu", "peito,",
    "Que,", "bem", "o", "vês,", "eterno", "me", "perdura.",
    "\"Amor", "nos", "igualou", "da", "morte", "o", "efeito:",
    "A", "quem", "no-la", "causou,", "Caína,", "esperas\".",
    "Após", "tais", "vozes", "foi", "silêncio", "feito.",
    "Daquelas", "almas", "as", "angústias", "feras",
    "Em", "meditar", "amargo", "a", "fronte", "inclino",
    "Té", "que", "o", "Mestre", "exclamou:", "\"Que", "consideras?\"",
    "Quando", "pude,", "falei:", "\"Cruel", "destino!",
    "Que", "doce", "cogitar!", "Que", "meigo", "encanto,",
    "Precederam", "do", "par", "o", "fim", "maligno!\"", "—",
    "Aos", "dois", "voltei-me", "e", "disse-lhes,", "entanto:",
    "\"Teus", "martírios,", "Francesca,", "me", "angustiam,",
    "Movem-me", "o", "triste,", "compassivo", "pranto.",
    "\"Quando", "os", "doces", "suspiros", "só", "se", "ouviam,",
    "Como,", "em", "que", "Amor", "mostrar-vos", "há", "querido",
    "Os", "desejos,", "que", "ainda", "se", "escondiam?\"", "—",
    "—", "\"Não", "há\"", "—", "disse", "—", "\"tormento", "mais", "dorido",
    "Que", "recordar", "o", "tempo", "venturoso",
    "Na", "desgraça.", "Teu", "Mestre", "o", "tem", "sentido.",
    "\"Mas", "porque", "de", "saber", "és", "desejoso,",
    "Como", "nasceu", "a", "flor", "do", "nosso", "afeto,",
    "Direi", "chorando", "o", "lance", "lastimoso.",
    "\"Por", "passatempo", "eu", "lia", "e", "o", "meu", "dileto",
    "De", "Lanceloto", "extremos", "namorados;",
    "Éramos", "sós,", "de", "coração", "quieto.",
    "\"Nossos", "olhos,", "por", "vezes", "encontrados,",
    "Cessam", "de", "ler;", "ao", "gesto", "a", "cor", "mudara.",
    "Um", "ponto", "só", "deu", "causa", "aos", "nossos", "fados.",
    "\"Ao", "lermos", "que", "nos", "lábios", "osculara",
    "O", "desejado", "riso,", "o", "heróico", "amante,",
    "Este,", "que", "mais", "de", "mim", "se", "não", "separa,",
    "\"A", "boca", "me", "beijou", "todo", "tremante,",
    "De", "Galeotto", "fez", "o", "autor", "e", "o", "escrito.",
    "Em", "ler", "não", "fomos", "nesse", "dia", "avante\".",
    "Enquanto", "a", "história", "triste", "um", "tinha", "dito,",
    "Tanto", "carpia", "o", "outro,", "que", "eu,", "absorto",
    "Em", "piedade,", "senti", "letal", "conflito,",
    "E", "tombei,", "como", "tomba", "corpo", "morto."
};



// Macro para calcular o número de elementos inseridos no array
#define TOTAL_PALAVRAS (sizeof(palavras_mais_usadas) / sizeof(palavras_mais_usadas[0]))

int main() {
    printf("Array de palavras carregado com sucesso!\n");
    printf("Total de palavras cadastradas: %ld\n\n", TOTAL_PALAVRAS);
    
    int t = time(NULL);

    for(int i = 0; i < 1000; i++)
    {    
        srand(t);
        printf("%s ", palavras_mais_usadas[rand() % TOTAL_PALAVRAS]);
        t++;
    }

    return 0;
}
